# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Team 3128 Aluminium Narwhals
email: info@team3128.org
description: > # this means to ignore newlines until "baseurl:"
  Copyright © 2018 Team 3128: Aluminum Narwhals
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://team3128.org" # the base hostname & protocol for your site
github_username: Team3128
excerpt_separator: ?more?

# Build settings
markdown: kramdown
